// SPDX-License-Identifier: GPL-3.0-or-later
#include "ai_movement_hooks.h"
#include "../core/globals.h"
#include "../core/log.h"
#include "../core/memory.h"
#include "../sdk/offsets.h"
#include "../sdk/scanner.h"
#include "../sdk/ue4.h"
#include <Windows.h>
#include <MinHook.h>
#include <atomic>
#include <cstring>
#include <mutex>
#include <unordered_map>
#include <vector>

namespace AiMovementHooks
{
namespace
{
    constexpr std::size_t kMoveSlot=0x410/sizeof(void*), kStopSlot=0x418/sizeof(void*), kCancelSlot=0x430/sizeof(void*);
    constexpr std::size_t kControllerStopSlot=0x728/sizeof(void*), kControllerMoveSlot=0x790/sizeof(void*), kControllerPathCommitSlot=0x798/sizeof(void*), kControllerPathBuildSlot=0x7A0/sizeof(void*);
    constexpr std::size_t kPathRequestSlot=0x428/sizeof(void*), kPathAbortSlot=0x460/sizeof(void*), kMovementCanStartSlot=0x548/sizeof(void*);
    constexpr std::size_t kTwinGenericMoveCall=0x18, kMoveHelperCall=0x275, kForceDispatcherCall=0x0C2, kTransitionCall=0x0DE;
    constexpr int kMixedAutomatic=0x1F98, kMixedCurrent=0x1FC2, kMixedForced=0x1FC3;

    using MoveToLocationFn=void(__fastcall*)(void*,const UE::FVector*,float,float,bool);
    using MixedTransitionFn=void(__fastcall*)(void*,std::uint8_t);
    using MoveRequestFn=void(__fastcall*)(void*,const void*,void*);
    using StopFn=void(__fastcall*)(void*,void*);
    using CancelFn=void(__fastcall*)(void*,void*);
    using ControllerStopFn=void(__fastcall*)(void*);
    using ControllerMoveFn=void*(__fastcall*)(void*,void*,const void*,void*);
    using ControllerPathCommitFn=void*(__fastcall*)(void*,void*,const void*,void*);
    using ControllerPathBuildFn=void(__fastcall*)(void*,const void*,const void*,void*);
    using PathRequestFn=void*(__fastcall*)(void*,void*,const void*,void*);
    using PathAbortFn=void(__fastcall*)(void*,const void*);
    using MovementCanStartFn=bool(__fastcall*)(void*);

    struct ClassHooks{void** vtable=nullptr;void* moveTarget=nullptr;void* stopTarget=nullptr;void* cancelTarget=nullptr;MoveRequestFn originalMove=nullptr;StopFn originalStop=nullptr;CancelFn originalCancel=nullptr;bool live=false;bool ownsInstallation=false;};
    struct Component{UE::UObject* guard=nullptr;UE::UObject* nav=nullptr;void** vtable=nullptr;bool mixed=false;bool owned=false;};
    struct ControllerClassHooks{void** vtable=nullptr;void* moveTarget=nullptr;void* stopTarget=nullptr;ControllerMoveFn originalMove=nullptr;ControllerStopFn originalStop=nullptr;ControllerPathCommitFn originalPathCommit=nullptr;ControllerPathBuildFn originalPathBuild=nullptr;ControllerMoveFn genericMove=nullptr;void* pathCommitTarget=nullptr;void* pathBuildTarget=nullptr;bool bypassTwinPostprocess=false;bool live=false;bool ownsInstallation=false;};
    struct PathClassHooks{void** vtable=nullptr;void* requestTarget=nullptr;void* abortTarget=nullptr;PathRequestFn originalRequest=nullptr;PathAbortFn originalAbort=nullptr;bool live=false;bool ownsInstallation=false;};
    struct MovementClassHooks{void** vtable=nullptr;void* canStartTarget=nullptr;MovementCanStartFn originalCanStart=nullptr;bool live=false;bool ownsInstallation=false;};
    struct MovementComponent{UE::UObject* guard=nullptr;UE::UObject* movement=nullptr;void** vtable=nullptr;bool forceCanStart=false;};
    struct ControllerComponent{UE::UObject* guard=nullptr;UE::UObject* controller=nullptr;void** vtable=nullptr;bool owned=false;};
    struct PathComponent{UE::UObject* guard=nullptr;UE::UObject* controller=nullptr;UE::UObject* pathFollower=nullptr;void** vtable=nullptr;};

    std::mutex g_mutex;
    std::vector<ClassHooks> g_classes;
    std::unordered_map<void*,Component> g_components;
    std::vector<ControllerClassHooks> g_controllerClasses;
    std::unordered_map<void*,ControllerComponent> g_controllers;
    std::vector<PathClassHooks> g_pathClasses;
    std::unordered_map<void*,PathComponent> g_pathFollowers;
    std::vector<MovementClassHooks> g_movementClasses;
    std::unordered_map<void*,MovementComponent> g_movements;
    MoveToLocationFn g_moveToLocation=nullptr;
    MixedTransitionFn g_mixedTransition=nullptr;
    std::atomic<std::uint64_t> g_nativeMoves{0},g_nativeStops{0},g_blockedMoves{0},g_blockedStops{0},g_blockedCancels{0},g_mixedTransitions{0};
    std::atomic<std::uint64_t> g_controllerMovesBlocked{0},g_controllerStopsBlocked{0},g_controllerMovesIssued{0},g_controllerStopsIssued{0},g_controllerMoveFaults{0};
    std::atomic<std::uint64_t> g_controllerMoveCalls{0},g_controllerPathCommits{0},g_controllerPathBuilds{0},g_pathRequests{0},g_pathAborts{0};
    std::atomic<std::uint64_t> g_twinGenericBypasses{0},g_twinOriginalMoveAttempts{0},g_twinOriginalMoveAccepted{0},g_twinGenericFallbacks{0},g_twinGenericFallbackAccepted{0};
    std::atomic<std::uint64_t> g_movementCanStartCalls{0},g_movementCanStartForced{0};
    thread_local bool t_internal=false,t_controllerInternal=false;

    std::uintptr_t Rva(const void* p){return p&&G::moduleBase?reinterpret_cast<std::uintptr_t>(p)-reinterpret_cast<std::uintptr_t>(G::moduleBase):0;}
    bool Bytes(const void* p,const std::uint8_t* expected,std::size_t size){return Scanner::IsExecutableAddress(p,size)&&std::memcmp(p,expected,size)==0;}
    void* NativeExec(UE::UObject* fn){if(!Mem::IsReadable(fn,Offsets::O_UFunction_ExecFunction+sizeof(void*)))return nullptr;void* exec=*reinterpret_cast<void**>(reinterpret_cast<std::uint8_t*>(fn)+Offsets::O_UFunction_ExecFunction);return Scanner::IsExecutableAddress(exec,16)?exec:nullptr;}
    ClassHooks* FindClassLocked(void* self){if(!Mem::IsReadable(self,sizeof(void*)))return nullptr;void** vt=*reinterpret_cast<void***>(self);for(ClassHooks& h:g_classes)if(h.vtable==vt)return &h;return nullptr;}
    Component* FindComponentLocked(void* self){auto it=g_components.find(self);return it==g_components.end()?nullptr:&it->second;}
    ControllerClassHooks* FindControllerClassLocked(void* self){if(!Mem::IsReadable(self,sizeof(void*)))return nullptr;void** vt=*reinterpret_cast<void***>(self);for(ControllerClassHooks& h:g_controllerClasses)if(h.vtable==vt)return &h;return nullptr;}
    PathClassHooks* FindPathClassLocked(void* self){if(!Mem::IsReadable(self,sizeof(void*)))return nullptr;void** vt=*reinterpret_cast<void***>(self);for(PathClassHooks& h:g_pathClasses)if(h.vtable==vt)return &h;return nullptr;}
    MovementClassHooks* FindMovementClassLocked(void* self){if(!Mem::IsReadable(self,sizeof(void*)))return nullptr;void** vt=*reinterpret_cast<void***>(self);for(MovementClassHooks& h:g_movementClasses)if(h.vtable==vt)return &h;return nullptr;}

    void __fastcall HkMoveRequest(void* self,const void* request,void* outId){MoveRequestFn original=nullptr;bool blocked=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ClassHooks* h=FindClassLocked(self))original=h->originalMove;if(Component* c=FindComponentLocked(self))blocked=c->owned&&!t_internal;}if(blocked){if(Mem::IsReadable(outId,sizeof(std::uint32_t)))*reinterpret_cast<std::uint32_t*>(outId)=0;g_blockedMoves.fetch_add(1,std::memory_order_relaxed);return;}if(original)original(self,request,outId);}
    void __fastcall HkStop(void* self,void* output){StopFn original=nullptr;bool blocked=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ClassHooks* h=FindClassLocked(self))original=h->originalStop;if(Component* c=FindComponentLocked(self))blocked=c->owned&&!t_internal;}if(blocked){g_blockedStops.fetch_add(1,std::memory_order_relaxed);return;}if(original)original(self,output);}
    void __fastcall HkCancel(void* self,void* reason){CancelFn original=nullptr;bool blocked=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ClassHooks* h=FindClassLocked(self))original=h->originalCancel;if(Component* c=FindComponentLocked(self))blocked=c->owned&&!t_internal;}if(blocked){g_blockedCancels.fetch_add(1,std::memory_order_relaxed);return;}if(original)original(self,reason);}
    void* SehControllerMove(ControllerMoveFn fn,void* self,void* result,const void* request,void* path){__try{return fn(self,result,request,path);}__except(EXCEPTION_EXECUTE_HANDLER){if(Mem::IsReadable(result,8))std::memset(result,0,8);g_controllerMoveFaults.fetch_add(1,std::memory_order_relaxed);return result;}}
    bool MoveResultAccepted(void* returned,void* result){const std::uint8_t* value=nullptr;if(Mem::IsReadable(returned,8))value=reinterpret_cast<const std::uint8_t*>(returned);else if(Mem::IsReadable(result,8))value=reinterpret_cast<const std::uint8_t*>(result);return value&&value[4]!=0;}
    void ZeroMoveResult(void* result){if(Mem::IsReadable(result,8))std::memset(result,0,8);}
    void SehControllerStop(ControllerStopFn fn,void* self){__try{fn(self);}__except(EXCEPTION_EXECUTE_HANDLER){}}
    void* __fastcall HkControllerMove(void* self,void* result,const void* request,void* path){ControllerMoveFn original=nullptr,generic=nullptr;bool blocked=false,registered=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ControllerClassHooks* h=FindControllerClassLocked(self)){original=h->originalMove;generic=h->bypassTwinPostprocess?h->genericMove:nullptr;}auto it=g_controllers.find(self);registered=it!=g_controllers.end();blocked=registered&&it->second.owned&&!t_controllerInternal;}if(registered)g_controllerMoveCalls.fetch_add(1,std::memory_order_relaxed);if(blocked){ZeroMoveResult(result);g_controllerMovesBlocked.fetch_add(1,std::memory_order_relaxed);return result;}if(registered&&generic&&original){g_twinOriginalMoveAttempts.fetch_add(1,std::memory_order_relaxed);void* ret=SehControllerMove(original,self,result,request,path);if(MoveResultAccepted(ret,result)){g_twinOriginalMoveAccepted.fetch_add(1,std::memory_order_relaxed);return ret;}if(generic!=original){ZeroMoveResult(result);g_twinGenericBypasses.fetch_add(1,std::memory_order_relaxed);g_twinGenericFallbacks.fetch_add(1,std::memory_order_relaxed);ret=SehControllerMove(generic,self,result,request,path);if(MoveResultAccepted(ret,result))g_twinGenericFallbackAccepted.fetch_add(1,std::memory_order_relaxed);return ret;}return ret;}return original?SehControllerMove(original,self,result,request,path):result;}
    bool __fastcall HkMovementCanStart(void* self){MovementCanStartFn original=nullptr;bool force=false;{std::lock_guard<std::mutex> lock(g_mutex);if(MovementClassHooks* h=FindMovementClassLocked(self))original=h->originalCanStart;auto it=g_movements.find(self);force=it!=g_movements.end()&&it->second.forceCanStart;}bool native=original?original(self):false;if(force){g_movementCanStartCalls.fetch_add(1,std::memory_order_relaxed);if(!native)g_movementCanStartForced.fetch_add(1,std::memory_order_relaxed);return true;}return native;}
    void* __fastcall HkControllerPathCommit(void* self,void* result,const void* request,void* path){ControllerPathCommitFn original=nullptr;bool registered=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ControllerClassHooks* h=FindControllerClassLocked(self))original=h->originalPathCommit;registered=g_controllers.find(self)!=g_controllers.end();}if(registered)g_controllerPathCommits.fetch_add(1,std::memory_order_relaxed);return original?original(self,result,request,path):result;}
    void __fastcall HkControllerPathBuild(void* self,const void* request,const void* query,void* outPath){ControllerPathBuildFn original=nullptr;bool registered=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ControllerClassHooks* h=FindControllerClassLocked(self))original=h->originalPathBuild;registered=g_controllers.find(self)!=g_controllers.end();}if(registered)g_controllerPathBuilds.fetch_add(1,std::memory_order_relaxed);if(original)original(self,request,query,outPath);}
    void* __fastcall HkPathRequest(void* self,void* result,const void* request,void* path){PathRequestFn original=nullptr;bool registered=false;{std::lock_guard<std::mutex> lock(g_mutex);if(PathClassHooks* h=FindPathClassLocked(self))original=h->originalRequest;registered=g_pathFollowers.find(self)!=g_pathFollowers.end();}if(registered)g_pathRequests.fetch_add(1,std::memory_order_relaxed);return original?original(self,result,request,path):result;}
    void __fastcall HkPathAbort(void* self,const void* reason){PathAbortFn original=nullptr;bool registered=false;{std::lock_guard<std::mutex> lock(g_mutex);if(PathClassHooks* h=FindPathClassLocked(self))original=h->originalAbort;registered=g_pathFollowers.find(self)!=g_pathFollowers.end();}if(registered)g_pathAborts.fetch_add(1,std::memory_order_relaxed);if(original)original(self,reason);}
    void __fastcall HkControllerStop(void* self){ControllerStopFn original=nullptr;bool blocked=false;{std::lock_guard<std::mutex> lock(g_mutex);if(ControllerClassHooks* h=FindControllerClassLocked(self))original=h->originalStop;auto it=g_controllers.find(self);blocked=it!=g_controllers.end()&&it->second.owned&&!t_controllerInternal;}if(blocked){g_controllerStopsBlocked.fetch_add(1,std::memory_order_relaxed);return;}if(original)SehControllerStop(original,self);}
    bool CreateHook(void* target,void* detour,void** original,const char* name){if(!Scanner::IsExecutableAddress(target,16)){LOG_HOOK("[AI-MOVE] %s refused: target is not executable.",name);return false;}MH_STATUS c=MH_CreateHook(target,detour,original);if(c!=MH_OK){LOG_HOOK("[AI-MOVE] %s refused: MH_CreateHook=%d.",name,c);return false;}MH_STATUS e=MH_EnableHook(target);if(e!=MH_OK&&e!=MH_ERROR_ENABLED){MH_RemoveHook(target);LOG_HOOK("[AI-MOVE] %s refused: MH_EnableHook=%d.",name,e);return false;}return true;}
    bool InstallClassHooksLocked(void** vt,ClassHooks& out){if(!Mem::IsReadable(vt,(kCancelSlot+1)*sizeof(void*)))return false;out.vtable=vt;out.moveTarget=vt[kMoveSlot];out.stopTarget=vt[kStopSlot];out.cancelTarget=vt[kCancelSlot];if(!CreateHook(out.moveTarget,reinterpret_cast<void*>(&HkMoveRequest),reinterpret_cast<void**>(&out.originalMove),"Mercuna.MoveRequest(+0x410)"))return false;if(!CreateHook(out.stopTarget,reinterpret_cast<void*>(&HkStop),reinterpret_cast<void**>(&out.originalStop),"Mercuna.Stop(+0x418)")){MH_DisableHook(out.moveTarget);MH_RemoveHook(out.moveTarget);return false;}if(!CreateHook(out.cancelTarget,reinterpret_cast<void*>(&HkCancel),reinterpret_cast<void**>(&out.originalCancel),"Mercuna.Cancel(+0x430)")){MH_DisableHook(out.stopTarget);MH_RemoveHook(out.stopTarget);MH_DisableHook(out.moveTarget);MH_RemoveHook(out.moveTarget);return false;}out.live=true;out.ownsInstallation=true;LOG_HOOK("[AI-MOVE] Mercuna detours LIVE: move=+0x%llX stop=+0x%llX cancel=+0x%llX (vtable-derived, sanity PASS).",(unsigned long long)Rva(out.moveTarget),(unsigned long long)Rva(out.stopTarget),(unsigned long long)Rva(out.cancelTarget));return true;}
    bool InstallControllerHooksLocked(void** vt,ControllerClassHooks& out){if(!Mem::IsReadable(vt,(kControllerPathBuildSlot+1)*sizeof(void*)))return false;out.vtable=vt;out.moveTarget=vt[kControllerMoveSlot];out.stopTarget=vt[kControllerStopSlot];out.pathCommitTarget=vt[kControllerPathCommitSlot];out.pathBuildTarget=vt[kControllerPathBuildSlot];static const std::uint8_t twinPrefix[]={0x48,0x89,0x5C,0x24,0x08,0x48,0x89,0x6C,0x24,0x18,0x56,0x57,0x41,0x56,0x48,0x83};static const std::uint8_t genericPrefix[]={0x40,0x55,0x56,0x57,0x41,0x54,0x41,0x55,0x41,0x57,0x48,0x8D,0x6C,0x24,0x88,0x48};auto* moveBytes=reinterpret_cast<std::uint8_t*>(out.moveTarget);if(Bytes(moveBytes,twinPrefix,sizeof(twinPrefix))&&Scanner::IsExecutableAddress(moveBytes+kTwinGenericMoveCall,5)&&moveBytes[kTwinGenericMoveCall]==0xE8){std::uint8_t* generic=Scanner::DecodeRel32CallTarget(moveBytes+kTwinGenericMoveCall);if(generic&&Bytes(generic,genericPrefix,sizeof(genericPrefix))){out.genericMove=reinterpret_cast<ControllerMoveFn>(generic);out.bypassTwinPostprocess=true;LOG_HOOK("[AI-CHAIN] Hook Twin generic controller move resolved: override=+0x%llX generic=+0x%llX; native-first fallback enabled.",(unsigned long long)Rva(out.moveTarget),(unsigned long long)Rva(generic));}}if(!CreateHook(out.moveTarget,reinterpret_cast<void*>(&HkControllerMove),reinterpret_cast<void**>(&out.originalMove),"AIController.MoveRequest(+0x790)"))return false;if(!CreateHook(out.stopTarget,reinterpret_cast<void*>(&HkControllerStop),reinterpret_cast<void**>(&out.originalStop),"Controller.StopMovement(+0x728)")){MH_DisableHook(out.moveTarget);MH_RemoveHook(out.moveTarget);return false;}if(!CreateHook(out.pathCommitTarget,reinterpret_cast<void*>(&HkControllerPathCommit),reinterpret_cast<void**>(&out.originalPathCommit),"AIController.CommitPath(+0x798)")){MH_DisableHook(out.stopTarget);MH_RemoveHook(out.stopTarget);MH_DisableHook(out.moveTarget);MH_RemoveHook(out.moveTarget);return false;}if(!CreateHook(out.pathBuildTarget,reinterpret_cast<void*>(&HkControllerPathBuild),reinterpret_cast<void**>(&out.originalPathBuild),"AIController.BuildPath(+0x7A0)")){MH_DisableHook(out.pathCommitTarget);MH_RemoveHook(out.pathCommitTarget);MH_DisableHook(out.stopTarget);MH_RemoveHook(out.stopTarget);MH_DisableHook(out.moveTarget);MH_RemoveHook(out.moveTarget);return false;}out.live=true;out.ownsInstallation=true;LOG_HOOK("[AI-MOVE] controller chain LIVE: move=+0x%llX commit=+0x%llX build=+0x%llX stop=+0x%llX.",(unsigned long long)Rva(out.moveTarget),(unsigned long long)Rva(out.pathCommitTarget),(unsigned long long)Rva(out.pathBuildTarget),(unsigned long long)Rva(out.stopTarget));return true;}
    bool InstallMovementHooksLocked(void** vt,MovementClassHooks& out){if(!Mem::IsReadable(vt,(kMovementCanStartSlot+1)*sizeof(void*)))return false;out.vtable=vt;out.canStartTarget=vt[kMovementCanStartSlot];if(!CreateHook(out.canStartTarget,reinterpret_cast<void*>(&HkMovementCanStart),reinterpret_cast<void**>(&out.originalCanStart),"NavMovement.CanStartPathFollowing(+0x548)"))return false;out.live=true;out.ownsInstallation=true;LOG_HOOK("[AI-CHAIN] Hook Twin movement-consumer gate LIVE: canStart=+0x%llX.",(unsigned long long)Rva(out.canStartTarget));return true;}
    bool RegisterMovementGateLocked(UE::UObject* guard,UE::UObject* movement){if(!Mem::IsReadable(movement,sizeof(void*)))return true;void** movementVt=*reinterpret_cast<void***>(movement);if(!Mem::IsReadable(movementVt,(kMovementCanStartSlot+1)*sizeof(void*)))return false;MovementClassHooks* movementHooks=nullptr;for(MovementClassHooks& h:g_movementClasses)if(h.vtable==movementVt){movementHooks=&h;break;}if(!movementHooks){MovementClassHooks candidate{};candidate.vtable=movementVt;candidate.canStartTarget=movementVt[kMovementCanStartSlot];for(const MovementClassHooks& installed:g_movementClasses){if(!installed.live||installed.canStartTarget!=candidate.canStartTarget)continue;candidate.originalCanStart=installed.originalCanStart;candidate.live=true;LOG_HOOK("[AI-CHAIN] movement vtable alias reused Hook Twin gate detour: vtable=%p.",movementVt);break;}if(!candidate.live&&!InstallMovementHooksLocked(movementVt,candidate))return false;g_movementClasses.push_back(candidate);movementHooks=&g_movementClasses.back();}if(!movementHooks->live)return false;MovementComponent& m=g_movements[movement];m.guard=guard;m.movement=movement;m.vtable=movementVt;m.forceCanStart=true;return true;}
    bool InstallPathHooksLocked(void** vt,PathClassHooks& out){if(!Mem::IsReadable(vt,(kPathAbortSlot+1)*sizeof(void*)))return false;out.vtable=vt;out.requestTarget=vt[kPathRequestSlot];out.abortTarget=vt[kPathAbortSlot];if(!CreateHook(out.requestTarget,reinterpret_cast<void*>(&HkPathRequest),reinterpret_cast<void**>(&out.originalRequest),"PathFollowing.RequestMove(+0x428)"))return false;if(!CreateHook(out.abortTarget,reinterpret_cast<void*>(&HkPathAbort),reinterpret_cast<void**>(&out.originalAbort),"PathFollowing.AbortMove(+0x460)")){MH_DisableHook(out.requestTarget);MH_RemoveHook(out.requestTarget);return false;}out.live=true;out.ownsInstallation=true;LOG_HOOK("[AI-MOVE] path-follow chain LIVE: request=+0x%llX abort=+0x%llX.",(unsigned long long)Rva(out.requestTarget),(unsigned long long)Rva(out.abortTarget));return true;}
}

bool ResolveHelpers(UE::UObject* moveFn,UE::UObject* forceFn)
{
    std::lock_guard<std::mutex> lock(g_mutex);
    if(!g_moveToLocation&&moveFn){auto* exec=static_cast<std::uint8_t*>(NativeExec(moveFn));static const std::uint8_t execPrefix[]={0x48,0x89,0x5C,0x24,0x08,0x48,0x89,0x6C,0x24,0x18,0x56,0x57,0x41,0x56,0x48,0x83};static const std::uint8_t targetPrefix[]={0x4C,0x8B,0xDC,0x48,0x83,0xEC,0x68,0x8B,0x42,0x08,0x45,0x33,0xC0};if(exec&&Bytes(exec,execPrefix,sizeof(execPrefix))&&Scanner::IsExecutableAddress(exec+kMoveHelperCall,5)&&exec[kMoveHelperCall]==0xE8){std::uint8_t* target=Scanner::DecodeRel32CallTarget(exec+kMoveHelperCall);if(target&&Bytes(target,targetPrefix,sizeof(targetPrefix))){g_moveToLocation=reinterpret_cast<MoveToLocationFn>(target);LOG_HOOK("[AI-MOVE] Mercuna MoveToLocation helper resolved via ReVa-confirmed callsite -> RVA 0x%llX, sanity PASS.",(unsigned long long)Rva(target));}}if(!g_moveToLocation)LOG_HOOK("[AI-MOVE] Mercuna MoveToLocation helper refused: callsite/target sanity failed.");}
    if(!g_mixedTransition&&forceFn){auto* exec=static_cast<std::uint8_t*>(NativeExec(forceFn));static const std::uint8_t execPrefix[]={0x48,0x89,0x5C,0x24,0x10,0x57,0x48,0x83,0xEC,0x20,0x48,0x8B,0xDA};static const std::uint8_t dispatcherPrefix[]={0x4C,0x8B,0xDC,0x49,0x89,0x5B,0x08,0x57,0x48,0x81,0xEC,0xC0,0x00,0x00,0x00};static const std::uint8_t transitionPrefix[]={0x40,0x53,0x57,0x48,0x83,0xEC,0x28,0x48,0x8B,0x81,0xA0,0x1F,0x00,0x00,0x0F,0xB6,0xFA};if(exec&&Bytes(exec,execPrefix,sizeof(execPrefix))&&Scanner::IsExecutableAddress(exec+kForceDispatcherCall,5)&&exec[kForceDispatcherCall]==0xE8){std::uint8_t* dispatcher=Scanner::DecodeRel32CallTarget(exec+kForceDispatcherCall);if(dispatcher&&Bytes(dispatcher,dispatcherPrefix,sizeof(dispatcherPrefix))&&Scanner::IsExecutableAddress(dispatcher+kTransitionCall,5)&&dispatcher[kTransitionCall]==0xE8){std::uint8_t* transition=Scanner::DecodeRel32CallTarget(dispatcher+kTransitionCall);if(transition&&Bytes(transition,transitionPrefix,sizeof(transitionPrefix))){g_mixedTransition=reinterpret_cast<MixedTransitionFn>(transition);LOG_HOOK("[AI-MOVE] Twin mixed-nav transition resolved via two-stage ReVa callsite chain -> RVA 0x%llX, sanity PASS.",(unsigned long long)Rva(transition));}}}if(!g_mixedTransition)LOG_HOOK("[AI-MOVE] Twin mixed-nav transition refused: callsite chain/target sanity failed.");}
    return g_moveToLocation!=nullptr;
}

bool RegisterMercunaComponent(UE::UObject* guard,UE::UObject* nav,bool mixed)
{
    if(!Mem::IsReadable(guard,0x30)||!Mem::IsReadable(nav,sizeof(void*)))return false;void** vt=*reinterpret_cast<void***>(nav);if(!Mem::IsReadable(vt,(kCancelSlot+1)*sizeof(void*)))return false;std::lock_guard<std::mutex> lock(g_mutex);ClassHooks* hooks=nullptr;for(ClassHooks& h:g_classes)if(h.vtable==vt){hooks=&h;break;}if(!hooks){ClassHooks candidate{};candidate.vtable=vt;candidate.moveTarget=vt[kMoveSlot];candidate.stopTarget=vt[kStopSlot];candidate.cancelTarget=vt[kCancelSlot];for(const ClassHooks& installed:g_classes){if(!installed.live||installed.moveTarget!=candidate.moveTarget||installed.stopTarget!=candidate.stopTarget||installed.cancelTarget!=candidate.cancelTarget)continue;candidate.originalMove=installed.originalMove;candidate.originalStop=installed.originalStop;candidate.originalCancel=installed.originalCancel;candidate.live=true;LOG_HOOK("[AI-MOVE] Mercuna vtable alias reused existing detours: vtable=%p.",vt);break;}if(!candidate.live&&!InstallClassHooksLocked(vt,candidate)){LOG_HOOK("[AI-MOVE] component registration refused: guard=%p nav=%p detours incomplete.",guard,nav);return false;}g_classes.push_back(candidate);hooks=&g_classes.back();}if(!hooks->live)return false;Component& c=g_components[nav];c.guard=guard;c.nav=nav;c.vtable=vt;c.mixed=mixed;return true;
}
bool RegisterController(UE::UObject* guard,UE::UObject* controller)
{
    if(!Mem::IsReadable(guard,0x30)||!Mem::IsReadable(controller,sizeof(void*)))return false;void** vt=*reinterpret_cast<void***>(controller);if(!Mem::IsReadable(vt,(kControllerPathBuildSlot+1)*sizeof(void*)))return false;auto* controllerBytes=reinterpret_cast<std::uint8_t*>(controller);if(!Mem::IsReadable(controllerBytes+Offsets::AH::AICtrl_PathFollowing,sizeof(void*)))return false;auto* pathFollower=*reinterpret_cast<UE::UObject**>(controllerBytes+Offsets::AH::AICtrl_PathFollowing);if(!Mem::IsReadable(pathFollower,sizeof(void*)))return false;void** pathVt=*reinterpret_cast<void***>(pathFollower);if(!Mem::IsReadable(pathVt,(kPathAbortSlot+1)*sizeof(void*)))return false;UE::UObject* movement=nullptr;auto* pathBytes=reinterpret_cast<std::uint8_t*>(pathFollower);if(Mem::IsReadable(pathBytes+Offsets::AH::PathFollow_MovementComp,sizeof(void*)))movement=*reinterpret_cast<UE::UObject**>(pathBytes+Offsets::AH::PathFollow_MovementComp);UE::UObject* characterMovement=nullptr;auto* guardBytes=reinterpret_cast<std::uint8_t*>(guard);if(Mem::IsReadable(guardBytes+Offsets::AH::Char_CharacterMovement,sizeof(void*))){characterMovement=*reinterpret_cast<UE::UObject**>(guardBytes+Offsets::AH::Char_CharacterMovement);if(!Mem::IsReadable(characterMovement,sizeof(void*)))characterMovement=nullptr;}
    std::lock_guard<std::mutex> lock(g_mutex);
    ControllerClassHooks* hooks=nullptr;for(ControllerClassHooks& h:g_controllerClasses)if(h.vtable==vt){hooks=&h;break;}if(!hooks){ControllerClassHooks candidate{};candidate.vtable=vt;candidate.moveTarget=vt[kControllerMoveSlot];candidate.stopTarget=vt[kControllerStopSlot];candidate.pathCommitTarget=vt[kControllerPathCommitSlot];candidate.pathBuildTarget=vt[kControllerPathBuildSlot];for(const ControllerClassHooks& installed:g_controllerClasses){if(!installed.live||installed.moveTarget!=candidate.moveTarget||installed.stopTarget!=candidate.stopTarget||installed.pathCommitTarget!=candidate.pathCommitTarget||installed.pathBuildTarget!=candidate.pathBuildTarget)continue;candidate.originalMove=installed.originalMove;candidate.originalStop=installed.originalStop;candidate.originalPathCommit=installed.originalPathCommit;candidate.originalPathBuild=installed.originalPathBuild;candidate.genericMove=installed.genericMove;candidate.bypassTwinPostprocess=installed.bypassTwinPostprocess;candidate.live=true;LOG_HOOK("[AI-MOVE] controller vtable alias reused existing chain detours: vtable=%p.",vt);break;}if(!candidate.live&&!InstallControllerHooksLocked(vt,candidate))return false;g_controllerClasses.push_back(candidate);hooks=&g_controllerClasses.back();}if(!hooks->live)return false;
    PathClassHooks* pathHooks=nullptr;for(PathClassHooks& h:g_pathClasses)if(h.vtable==pathVt){pathHooks=&h;break;}if(!pathHooks){PathClassHooks candidate{};candidate.vtable=pathVt;candidate.requestTarget=pathVt[kPathRequestSlot];candidate.abortTarget=pathVt[kPathAbortSlot];for(const PathClassHooks& installed:g_pathClasses){if(!installed.live||installed.requestTarget!=candidate.requestTarget||installed.abortTarget!=candidate.abortTarget)continue;candidate.originalRequest=installed.originalRequest;candidate.originalAbort=installed.originalAbort;candidate.live=true;LOG_HOOK("[AI-MOVE] path-follow vtable alias reused existing detours: vtable=%p.",pathVt);break;}if(!candidate.live&&!InstallPathHooksLocked(pathVt,candidate))return false;g_pathClasses.push_back(candidate);pathHooks=&g_pathClasses.back();}if(!pathHooks->live)return false;
    if(hooks->bypassTwinPostprocess){bool hasCandidate=Mem::IsReadable(movement,sizeof(void*))||Mem::IsReadable(characterMovement,sizeof(void*));if(!hasCandidate){LOG_HOOK("[AI-CHAIN] Hook Twin movement-consumer gate refused: no readable path/character movement guard=%p controller=%p.",guard,controller);return false;}if(!RegisterMovementGateLocked(guard,movement))return false;if(characterMovement!=movement&&!RegisterMovementGateLocked(guard,characterMovement))return false;}
    ControllerComponent& c=g_controllers[controller];c.guard=guard;c.controller=controller;c.vtable=vt;PathComponent& p=g_pathFollowers[pathFollower];p.guard=guard;p.controller=controller;p.pathFollower=pathFollower;p.vtable=pathVt;return true;
}

void UnregisterGuard(UE::UObject* guard){std::lock_guard<std::mutex> lock(g_mutex);for(auto it=g_components.begin();it!=g_components.end();)if(it->second.guard==guard)it=g_components.erase(it);else ++it;for(auto it=g_controllers.begin();it!=g_controllers.end();)if(it->second.guard==guard)it=g_controllers.erase(it);else ++it;for(auto it=g_pathFollowers.begin();it!=g_pathFollowers.end();)if(it->second.guard==guard)it=g_pathFollowers.erase(it);else ++it;for(auto it=g_movements.begin();it!=g_movements.end();)if(it->second.guard==guard)it=g_movements.erase(it);else ++it;}
void SetMercunaOwned(UE::UObject* guard,UE::UObject* nav,bool owned){std::lock_guard<std::mutex> lock(g_mutex);auto it=g_components.find(nav);if(it!=g_components.end()&&it->second.guard==guard)it->second.owned=owned;}
void SetControllerOwned(UE::UObject* guard,UE::UObject* controller,bool owned){std::lock_guard<std::mutex> lock(g_mutex);auto it=g_controllers.find(controller);if(it!=g_controllers.end()&&it->second.guard==guard)it->second.owned=owned;}
void SetControllerCallInternal(bool internal){t_controllerInternal=internal;}

bool ControllerMoveToActor(UE::UObject* guard,UE::UObject* controller,UE::UObject* goal,float acceptanceRadius)
{
    ControllerMoveFn original=nullptr;bool owned=false;{std::lock_guard<std::mutex> lock(g_mutex);auto it=g_controllers.find(controller);owned=it!=g_controllers.end()&&it->second.guard==guard&&it->second.owned;if(ControllerClassHooks* h=FindControllerClassLocked(controller))original=h->originalMove;}if(!owned||!original||!Mem::IsReadable(goal,0x30))return false;
    struct alignas(8) NativeMoveRequest{void* goalActor;UE::FVector goalLocation;std::uint32_t locationPad;void* filterClass;std::uint32_t flags;float acceptance;std::uint64_t userFlags;void* pathShared;std::uint32_t tail;std::uint32_t tailPad;} request{};static_assert(sizeof(NativeMoveRequest)==0x40,"ReVa-mapped FAIMoveRequest size changed");
    request.goalActor=goal;request.goalLocation={3.402823466e+38F,3.402823466e+38F,3.402823466e+38F};auto* controllerBytes=reinterpret_cast<std::uint8_t*>(controller);if(Mem::IsReadable(controllerBytes+0x328,sizeof(void*)))request.filterClass=*reinterpret_cast<void**>(controllerBytes+0x328);request.flags=0x7F;request.acceptance=acceptanceRadius;alignas(8) std::uint8_t result[8]{};void* returned=nullptr;try{t_controllerInternal=true;returned=SehControllerMove(original,controller,result,&request,nullptr);t_controllerInternal=false;}catch(...){t_controllerInternal=false;return false;}bool ok=MoveResultAccepted(returned,result);if(ok)g_controllerMovesIssued.fetch_add(1,std::memory_order_relaxed);return ok;
}

bool ControllerStop(UE::UObject* guard,UE::UObject* controller){ControllerStopFn original=nullptr;bool owned=false;{std::lock_guard<std::mutex> lock(g_mutex);auto it=g_controllers.find(controller);owned=it!=g_controllers.end()&&it->second.guard==guard&&it->second.owned;if(ControllerClassHooks* h=FindControllerClassLocked(controller))original=h->originalStop;}if(!owned||!original)return false;try{t_controllerInternal=true;original(controller);t_controllerInternal=false;g_controllerStopsIssued.fetch_add(1,std::memory_order_relaxed);return true;}catch(...){t_controllerInternal=false;return false;}}
bool OwnsGuard(UE::UObject* guard){std::lock_guard<std::mutex> lock(g_mutex);for(const auto& pair:g_components)if(pair.second.guard==guard&&pair.second.owned)return true;for(const auto& pair:g_controllers)if(pair.second.guard==guard&&pair.second.owned)return true;return false;}
UE::UObject* RegisteredNavigation(UE::UObject* guard){std::lock_guard<std::mutex> lock(g_mutex);for(const auto& pair:g_components)if(pair.second.guard==guard)return pair.second.nav;return nullptr;}

bool MoveToLocation(UE::UObject* nav,const UE::FVector& destination,float endDistance,float speed,bool partial){MoveToLocationFn helper=nullptr;bool owned=false;{std::lock_guard<std::mutex> lock(g_mutex);auto it=g_components.find(nav);owned=it!=g_components.end()&&it->second.owned;helper=g_moveToLocation;}if(!owned||!helper||!Mem::IsReadable(nav,0x30))return false;bool ok=false;try{t_internal=true;helper(nav,&destination,endDistance,speed,partial);t_internal=false;ok=true;}catch(...){t_internal=false;LOG_HOOK("[AI-MOVE] native Mercuna MoveToLocation exception: nav=%p.",nav);}if(ok)g_nativeMoves.fetch_add(1,std::memory_order_relaxed);return ok;}
bool Stop(UE::UObject* nav){StopFn original=nullptr;{std::lock_guard<std::mutex> lock(g_mutex);auto it=g_components.find(nav);if(it==g_components.end()||!it->second.owned)return false;if(ClassHooks* h=FindClassLocked(nav))original=h->originalStop;}if(!original)return false;alignas(16) std::uint8_t output[32]{};bool ok=false;try{t_internal=true;original(nav,output);t_internal=false;ok=true;}catch(...){t_internal=false;LOG_HOOK("[AI-MOVE] native Mercuna Stop exception: nav=%p.",nav);}if(ok)g_nativeStops.fetch_add(1,std::memory_order_relaxed);return ok;}

bool ForceMixedNavigation(UE::UObject* guard,std::uint8_t mode){MixedTransitionFn transition=nullptr;{std::lock_guard<std::mutex> lock(g_mutex);transition=g_mixedTransition;}auto* base=reinterpret_cast<std::uint8_t*>(guard);if(!transition||(mode!=1&&mode!=2)||!Mem::IsReadable(base+kMixedForced,1))return false;bool ok=false;try{base[kMixedAutomatic]=0;base[kMixedForced]=1;transition(guard,mode);ok=base[kMixedCurrent]==mode;}catch(...){ok=false;}if(ok)g_mixedTransitions.fetch_add(1,std::memory_order_relaxed);else LOG_HOOK("[AI-MOVE] Twin transition to mode %u failed/refused: guard=%p.",(unsigned)mode,guard);return ok;}
bool SetMixedAutomatic(UE::UObject* guard,bool automatic){auto* base=reinterpret_cast<std::uint8_t*>(guard);if(!Mem::IsReadable(base+kMixedForced,1))return false;base[kMixedAutomatic]=automatic?1:0;base[kMixedForced]=automatic?0:1;return true;}
std::uint8_t CurrentMixedNavigation(UE::UObject* guard){auto* p=reinterpret_cast<std::uint8_t*>(guard)+kMixedCurrent;return Mem::IsReadable(p,1)?*p:0;}

Status GetStatus()
{
    Status s{};std::lock_guard<std::mutex> lock(g_mutex);s.moveHelperResolved=g_moveToLocation!=nullptr;s.mixedTransitionResolved=g_mixedTransition!=nullptr;s.moveHelper=reinterpret_cast<std::uintptr_t>(g_moveToLocation);s.mixedTransition=reinterpret_cast<std::uintptr_t>(g_mixedTransition);s.registeredComponents=(int)(g_components.size()+g_controllers.size());s.registeredPathFollowers=(int)g_pathFollowers.size();s.registeredMovementComponents=(int)g_movements.size();for(const auto& pair:g_components)if(pair.second.owned)++s.ownedComponents;for(const auto& pair:g_controllers)if(pair.second.owned)++s.ownedComponents;
    for(const ClassHooks& h:g_classes){if(!h.live)continue;s.mercunaDetoursLive=true;if(!s.moveRequestTarget){s.moveRequestTarget=reinterpret_cast<std::uintptr_t>(h.moveTarget);s.stopTarget=reinterpret_cast<std::uintptr_t>(h.stopTarget);s.cancelTarget=reinterpret_cast<std::uintptr_t>(h.cancelTarget);}}
    for(const ControllerClassHooks& h:g_controllerClasses){if(!h.live)continue;s.controllerDetoursLive=true;if(!s.controllerMoveTarget){s.controllerMoveTarget=reinterpret_cast<std::uintptr_t>(h.moveTarget);s.controllerStopTarget=reinterpret_cast<std::uintptr_t>(h.stopTarget);s.controllerPathCommitTarget=reinterpret_cast<std::uintptr_t>(h.pathCommitTarget);s.controllerPathBuildTarget=reinterpret_cast<std::uintptr_t>(h.pathBuildTarget);}}
    for(const PathClassHooks& h:g_pathClasses){if(!h.live)continue;if(!s.pathRequestTarget){s.pathRequestTarget=reinterpret_cast<std::uintptr_t>(h.requestTarget);s.pathAbortTarget=reinterpret_cast<std::uintptr_t>(h.abortTarget);}}
    for(const MovementClassHooks& h:g_movementClasses){if(!h.live||s.movementCanStartTarget)continue;s.movementCanStartTarget=reinterpret_cast<std::uintptr_t>(h.canStartTarget);}
    s.nativeMovesIssued=g_nativeMoves.load(std::memory_order_relaxed);s.nativeStopsIssued=g_nativeStops.load(std::memory_order_relaxed);s.externalMovesBlocked=g_blockedMoves.load(std::memory_order_relaxed);s.externalStopsBlocked=g_blockedStops.load(std::memory_order_relaxed);s.externalCancelsBlocked=g_blockedCancels.load(std::memory_order_relaxed);s.mixedTransitions=g_mixedTransitions.load(std::memory_order_relaxed);s.controllerMovesBlocked=g_controllerMovesBlocked.load(std::memory_order_relaxed);s.controllerStopsBlocked=g_controllerStopsBlocked.load(std::memory_order_relaxed);s.controllerMovesIssued=g_controllerMovesIssued.load(std::memory_order_relaxed);s.controllerStopsIssued=g_controllerStopsIssued.load(std::memory_order_relaxed);s.controllerMoveCalls=g_controllerMoveCalls.load(std::memory_order_relaxed);s.controllerPathCommits=g_controllerPathCommits.load(std::memory_order_relaxed);s.controllerPathBuilds=g_controllerPathBuilds.load(std::memory_order_relaxed);s.pathRequests=g_pathRequests.load(std::memory_order_relaxed);s.pathAborts=g_pathAborts.load(std::memory_order_relaxed);s.twinGenericBypasses=g_twinGenericBypasses.load(std::memory_order_relaxed);s.twinOriginalMoveAttempts=g_twinOriginalMoveAttempts.load(std::memory_order_relaxed);s.twinOriginalMoveAccepted=g_twinOriginalMoveAccepted.load(std::memory_order_relaxed);s.twinGenericFallbacks=g_twinGenericFallbacks.load(std::memory_order_relaxed);s.twinGenericFallbackAccepted=g_twinGenericFallbackAccepted.load(std::memory_order_relaxed);s.movementCanStartCalls=g_movementCanStartCalls.load(std::memory_order_relaxed);s.movementCanStartForced=g_movementCanStartForced.load(std::memory_order_relaxed);return s;
}

void DumpStatus()
{
    Status s=GetStatus();LOG_HOOK("[AI-MOVE] helper=%d RVA=0x%llX mixed=%d RVA=0x%llX mercunaDetours=%d move=0x%llX stop=0x%llX cancel=0x%llX controllerDetours=%d ctrlMove=0x%llX ctrlStop=0x%llX components=%d owned=%d mercIssued=%llu/%llu blocked=%llu/%llu/%llu ctrlIssued=%llu/%llu ctrlBlocked=%llu/%llu transitions=%llu",s.moveHelperResolved?1:0,(unsigned long long)Rva((void*)s.moveHelper),s.mixedTransitionResolved?1:0,(unsigned long long)Rva((void*)s.mixedTransition),s.mercunaDetoursLive?1:0,(unsigned long long)Rva((void*)s.moveRequestTarget),(unsigned long long)Rva((void*)s.stopTarget),(unsigned long long)Rva((void*)s.cancelTarget),s.controllerDetoursLive?1:0,(unsigned long long)Rva((void*)s.controllerMoveTarget),(unsigned long long)Rva((void*)s.controllerStopTarget),s.registeredComponents,s.ownedComponents,(unsigned long long)s.nativeMovesIssued,(unsigned long long)s.nativeStopsIssued,(unsigned long long)s.externalMovesBlocked,(unsigned long long)s.externalStopsBlocked,(unsigned long long)s.externalCancelsBlocked,(unsigned long long)s.controllerMovesIssued,(unsigned long long)s.controllerStopsIssued,(unsigned long long)s.controllerMovesBlocked,(unsigned long long)s.controllerStopsBlocked,(unsigned long long)s.mixedTransitions);
    LOG_HOOK("[AI-MOVE] controller +0x790 empty-route crash faults firewalled: %llu",(unsigned long long)g_controllerMoveFaults.load(std::memory_order_relaxed));
    LOG_HOOK("[AI-CHAIN] ctrl move/commit/build=%llu/%llu/%llu targets=+0x%llX/+0x%llX/+0x%llX | path request/abort=%llu/%llu targets=+0x%llX/+0x%llX registered=%zu",(unsigned long long)s.controllerMoveCalls,(unsigned long long)s.controllerPathCommits,(unsigned long long)s.controllerPathBuilds,(unsigned long long)Rva((void*)s.controllerMoveTarget),(unsigned long long)Rva((void*)s.controllerPathCommitTarget),(unsigned long long)Rva((void*)s.controllerPathBuildTarget),(unsigned long long)s.pathRequests,(unsigned long long)s.pathAborts,(unsigned long long)Rva((void*)s.pathRequestTarget),(unsigned long long)Rva((void*)s.pathAbortTarget),(size_t)s.registeredPathFollowers);
    LOG_HOOK("[AI-CHAIN] Twin original move accepted=%llu/%llu | generic fallback accepted=%llu/%llu bypasses=%llu | movement canStart calls/forced=%llu/%llu target=+0x%llX registered=%d",(unsigned long long)s.twinOriginalMoveAccepted,(unsigned long long)s.twinOriginalMoveAttempts,(unsigned long long)s.twinGenericFallbackAccepted,(unsigned long long)s.twinGenericFallbacks,(unsigned long long)s.twinGenericBypasses,(unsigned long long)s.movementCanStartCalls,(unsigned long long)s.movementCanStartForced,(unsigned long long)Rva((void*)s.movementCanStartTarget),s.registeredMovementComponents);
}

void Shutdown()
{
    std::lock_guard<std::mutex> lock(g_mutex);for(ClassHooks& h:g_classes){if(!h.live||!h.ownsInstallation)continue;MH_DisableHook(h.cancelTarget);MH_RemoveHook(h.cancelTarget);MH_DisableHook(h.stopTarget);MH_RemoveHook(h.stopTarget);MH_DisableHook(h.moveTarget);MH_RemoveHook(h.moveTarget);h.live=false;}for(ControllerClassHooks& h:g_controllerClasses){if(!h.live||!h.ownsInstallation)continue;MH_DisableHook(h.pathBuildTarget);MH_RemoveHook(h.pathBuildTarget);MH_DisableHook(h.pathCommitTarget);MH_RemoveHook(h.pathCommitTarget);MH_DisableHook(h.stopTarget);MH_RemoveHook(h.stopTarget);MH_DisableHook(h.moveTarget);MH_RemoveHook(h.moveTarget);h.live=false;}for(MovementClassHooks& h:g_movementClasses){if(!h.live||!h.ownsInstallation)continue;MH_DisableHook(h.canStartTarget);MH_RemoveHook(h.canStartTarget);h.live=false;}for(PathClassHooks& h:g_pathClasses){if(!h.live||!h.ownsInstallation)continue;MH_DisableHook(h.abortTarget);MH_RemoveHook(h.abortTarget);MH_DisableHook(h.requestTarget);MH_RemoveHook(h.requestTarget);h.live=false;}g_classes.clear();g_components.clear();g_controllerClasses.clear();g_controllers.clear();g_pathClasses.clear();g_pathFollowers.clear();g_movementClasses.clear();g_movements.clear();g_moveToLocation=nullptr;g_mixedTransition=nullptr;
}
}
